### GET API
GET http://localhost:99/ HTTP/1.1

### GET all users
GET http://localhost:99/users HTTP/1.1

### Adding user
POST http://localhost:99/users HTTP/1.1 
content-type: application/json

{
    "username": "aaa",
	"email": "aaa@aaa.com",
	"password": "aaa"
}

### Changing user
PUT http://localhost:99/users/5 HTTP/1.1 
content-type: application/json

{
    "username": "xxx",
	"email": "xxx@xxx.com",
    "password": "xxx"
}

### Delete user
DELETE http://localhost:99/users/6 HTTP/1.1

### Send password reset e-mail
POST http://localhost:99/users/password/email HTTP/1.1
content-type: application/json

{
	"email": "xxx@xxx.com"
}

### Password recovery e-mail
GET http://localhost:99/users/password/email/003a7f70cf576e0a4e00/xxx@xxx.com HTTP/1.1

### Password update
PUT http://localhost:99/users/password/email/003a7f70cf576e0a4e00/xxx@xxx.com HTTP/1.1
content-type: application/json

{
	"newPassword": "bbbb"
}
